export default [
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: {
          copy: 'test',
          id: 'testing-library',
          index: 1,
        },
        subtitle: null,
        tags: null,
        title: 'post 1',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: {
          copy: 'test',
          id: 'testing-library',
          index: 2,
        },
        subtitle: null,
        tags: null,
        title: 'post 2',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 3',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 4',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 5',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 6',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 7',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 8',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 9',
      },
      id: null,
      timeToRead: null,
    },
  },
  {
    node: {
      fields: null,
      fileAbsolutePath: null,
      frontmatter: {
        date: null,
        description: null,
        image: null,
        series: null,
        subtitle: null,
        tags: null,
        title: 'post 10',
      },
      id: null,
      timeToRead: null,
    },
  },
];
